### PR TITLE
Updated the navbar

### PR DESCRIPTION
**Pull request by f-zahra**
added a conditional statement for the connexion button

### CODE REVIEW

**Review by Emimint — CHANGES_REQUESTED** [review]
@f-zahra it looks nice but it does not take into account the last changes from the development branch. Could you do the merge locally first?

**Review by Emimint — APPROVED** [review]
ok 👍

**Review by Emimint — APPROVED** [review]
good :)

**Review by cylia93 — APPROVED** [review]
Approve

**Pull request merged**
